# Generated by Django 5.0.6 on 2024-12-01 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_users_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
